version: "3.7"

services:
    virtuoso:
        image: tenforce/virtuoso
        environment:
            VIRT_Parameters_DirsAllowed: ., /usr/local/virtuoso-opensource/share/virtuoso/vad, /files
        volumes:
            - files:/files
            
    importer:
        build: ./
        command: /virtuoso/git_write.sh # Use whatever script you need here
        environment:
            DBA_PASSWORD: ${DBA_PASSWORD}
            VIRTUOSO_IMPORT_DIR: /virtuoso/data
            GIT_REPO: ${GIT_REPO}
            GRAPH_URI: ${GRAPH_URI}
            VIRTUOSO_EXPORT_DIR: /virtuoso/data
            GIT_DIRECTORY: /virtuoso/git
            GIT_EMAIL: ${GIT_EMAIL}
            GIT_NAME: ${GIT_NAME}
        volumes:
            - files:/virtuoso/data
            - ./id_rsa:/root/.ssh/id_rsa
            - ./config:/root/.ssh/config

volumes:
    files: {}
