version: "3.7"

services:
    virtuoso:
        image: tenforce/virtuoso
            
    importer:
        build: ./
        environment:
            DBA_PASSWORD: dba
            VIRTUOSO_IMPORT_DIR: /tmp
            GIT_REPO: https://github.com/AKSW/pfarrerbuch.jekyllrdf.git
